import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import PortalScene from "@/components/PortalScene";
// import CursorHandler from "@/components/CursorHandler";
// import { PortalProvider } from "@/context/PortalContext";
import Navbar from "@/components/Navbar";
import { ClickedProvider } from "@/context/ClickedProvider";
import { ThemeProvider } from "@/context/ThemeProvider";
// import { ThemeProvider } from "@/context/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <ClickedProvider>
          <body className="antialiased">
            <div className="text-foreground min-h-screen font-serif flex flex-col justify-between">
              <Navbar />
              <div className="h-8"/>
                {/* <PortalProvider> */}
                  {/* <CursorHandler> */}
                    {/* <PortalScene /> */}
                    <main>{children}</main>
                  {/* </CursorHandler> */}
                {/* </PortalProvider> */}
              <div className="h-24"/>
            </div>
          </body>
        </ClickedProvider>
      </ThemeProvider>
    </html>
  );
}
